# version: '3'

services:
  source_postgres:
    # Service for the source PostgreSQL database
    image: postgres:17.6
    # Use the official PostgreSQL image
    networks:
      # Define the network for the service
      - duke_elt_network
    environment:
      # Environment variables for PostgreSQL
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: secret
      POSTGRES_DB: source_db
    healthcheck:
      test: pg_isready -h localhost -U $$POSTGRES_USER
      interval: 2s
      timeout: 5s
      retries: 5
    ports:
      # Expose the PostgreSQL port 
      - "5435:5432"
    volumes:
      # Map the local directory to the container's init directory
      - ./source_db_init/init.sql:/docker-entrypoint-initdb.d/init.sql
      - type: bind
        source: db_data
        target: /var/lib/postgresql/sales_data
        read_only: false


#  target_postgres:
    # Service for the target PostgreSQL database
#    image: postgres:17.6
    # Use the official PostgreSQL image
#    networks:
      # Define the network for the service
#      - duke_elt_network
#    environment:
      # Environment variables for PostgreSQL
#      POSTGRES_USER: postgres
 #     POSTGRES_PASSWORD: secret
 #     POSTGRES_DB: target_db
 #   ports:
      # Expose the PostgreSQL port
#      - "5436:5432"
    # Don't need to initialize target volume until we know elt script works
    #volumes:
      # Map the local directory to the container's init directory
    #  - ./target_db_init/init.sql:/docker-entrypoint-initdb.d/init.sql

  # Service for the ETL script
  elt_script:
    # Build the Dockerfile in the current directory
    build:
      context: ./elt
      dockerfile: Dockerfile
    command: ["python", "elt_script.py"]
    stdin_open: true # docker run -i
    tty: true        # docker run -t
    networks:
      # Define the network for the service
      - duke_elt_network
    depends_on:
      # Ensure source_postgres is ready before running the script
      # This container won't start until dependencies are finished building
      - source_postgres
#      - target_postgres
    volumes:
      - type: bind
        source: db_data
        target: /sales_data
        read_only: false
    

  dbt: 
    image: ghcr.io/dbt-labs/dbt-postgres:latest
    # Use the official dbt image for PostgreSQL
    command:
      [
        "run",
        "--profiles-dir",
        "/root",
        "--project-dir",
        "/dbt"
      ]
    networks:
    # Define the network for the service
      - duke_elt_network
    volumes:
      # Map the local dbt project directory to the container's /dbt directory
      - ./duke_elt_project:/dbt 
      # Map the local profiles.yml to the container's /usr/app/ directory
      - ~/.dbt:/root #./elt_project/profiles.yml:/usr/app/profiles.yml
    depends_on:
      # Ensure target_postgres is ready before running dbt
      - elt_script
    environment:
      DBT_PROFILE: duke_elt_project
      DBT_TARGET: dev
    extra_hosts:
      - "host.docker.internal:host-gateway"


volumes:
  # Define any named volumes here if needed in the future
  db_data:
    driver: local
    driver_opts:
      type: none
      device: /Users/davidcleary/Data_Science/duke_elt_project/db_data
      o: bind



networks:
  duke_elt_network:
    # Define the network for the services
    driver: bridge

